<MyGrid>

    name: name
    age: age

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Name: "
            TextInput:
                id: name
                multiline:False
            Label:
                text:  "Age: "
            TextInput:
                id: age
                multiline:False
        Button:
            text:"Submit"
            on_press:root.btn()